[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.19.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["content/**", "public/**", "src/data/**"]
  node_bundler = "esbuild"
