[build]
  command = "npm run build"
  publish = ".next"

[build.environment]

  NODE_VERSION = "22.11.0"
  NODE_OPTIONS = "--max-old-space-size=4096"


[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["content/**", "public/**", "src/data/**"]
  node_bundler = "esbuild"
