name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.19.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.x
          cache: 'npm'

      - name: Verify Cloudflare directories
        run: |
          [ ! -d functions ] || ls functions
          [ ! -d workers ] || ls workers

      - name: Configure npm
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set strict-ssl true
          npm config set fetch-retries 5
          npm config set fetch-retry-mintimeout 10000
          npm config set fetch-retry-maxtimeout 60000
          npm config set audit false
          npm config set fund false

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        run: npm test

      - name: Build
        run: npm run build
